# Generated by Django 2.2.4 on 2019-08-03 03:04

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('age', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('F', 'femea'), ('M', 'macho')], default='F', max_length=1)),
                ('specie', models.CharField(choices=[('cachorro', 'cachorro'), ('gato', 'gato')], default='cachorro', max_length=225)),
                ('size', models.CharField(choices=[('pequeno', 'pequeno'), ('medio', 'medio'), ('grande', 'grande'), ('extra grande', 'extra grande')], default='pequeno', max_length=225)),
                ('category', models.CharField(choices=[('achado', 'achado'), ('perdido', 'perdido'), ('doação', 'doação')], default='achado', max_length=225)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
